// Generated by scripts/sync-package-versions.mjs from package.json.
// Do not edit by hand; run `npm run packages:version -- <version>`.

/** The npm name this package is published under. */
export const LIVE_PATCH_PACKAGE_NAME = '@alishaikh110/live-patch' as const;

/** The released version of this package, readable at runtime. */
export const LIVE_PATCH_PACKAGE_VERSION = '1.0.0' as const;
