// Generated by scripts/sync-package-versions.mjs from package.json.
// Do not edit by hand; run `npm run packages:version -- <version>`.

/** The npm name this package is published under. */
export const EXPERIENCE_COMPILER_PACKAGE_NAME = '@alishaikh110/experience-compiler' as const;

/** The released version of this package, readable at runtime. */
export const EXPERIENCE_COMPILER_PACKAGE_VERSION = '1.0.0' as const;
